[book]
authors = ["cr0mll"]
language = "en"
multilingual = false
src = "Notes"
title = "The Cyberclopaedia"

[preprocessor.inline-mathjax]
before = ["links", "index"]
renderer = ["html"]

[output.html]
no-section-label = true
default-theme = "ayu"
git-repository-url = "https://github.com/cr0mll/cyberclopaedia/"
git-repository-icon = "fa-github"
mathjax-support = true

[output.html.fold]
enable = true


[build]
build-dir = "docs"