[book]
authors = ["cr0mll"]
language = "en"
multilingual = false
src = "Notes"
title = "Master Hacking Notes"

[output.html]
no-section-label = true
default-theme = "navy"
git-repository-url = "https://github.com/cr0mll/master-hacking-notes/"
git-repository-icon = "fa-github"

[output.html.fold]
enable = true

[build]
build-dir = "docs"